### ISSUE TITLE
Compile using VS2015

### ISSUE THREAD

**Issue by Dial0** [Cultrarius/QuestWeaver#1]
Hi,
This look really interesting, I am interested in using this in a small concept project. 
I know the latest commit does not build, however would you be able to help me setup a visual studio project with the dependencies, when the project is stable again?

**Comment by Cultrarius** [comment]
Hey,
the build should be stable - travis is currently failing because the build is taking too long (because I have to recompile cmake with every build since the travis version is too old).

If you have any questions or problems I will be happy to help! :smiley:

**Comment by Dial0** [comment]
Awesome!

I ran cmake on Windows, with MSVC++ 14 as the compiler and it failed with;

CMake Error at CMakeModules/CodeCoverage.cmake:85 (MESSAGE):
  Compiler is not GNU gcc! Aborting...
Call Stack (most recent call first):
  CMakeLists.txt:14 (INCLUDE)

**Comment by Cultrarius** [comment]
Ah, I see.
The problem is very likely the code coverage module, which requires gcc to work. I adjusted the CMakeLists.txt and included a Windows version. Just open the file and delete all the "Version 1" (Linux) lines and uncomment the "Version 2" (Windows) lines and try to generate your project files again.

**Comment by Dial0** [comment]
Nice.

That did the trick,
I also have to add the /bigobj compiler option into the questweaver configuration within visual studio.

The compiler was also throwing errors about the MAX function being undefined, unless I added #include <algorithm> to those files.

Also had to add #include <iterator> to SpaceWorldModel.cpp as it was throwing an error about back_inserter().

Also the project configuration is being created with the GCC -03 compiler option, which MSVC doesn't recognise.


I will have a look at this over the next few days, do you have any notes/examples to do with creating the quest templates and how to integrate it into an existing game engine/world?

**Comment by Cultrarius** [comment]
Great, thanks - could you open a Pull Request, so I can merge your fix into the project? :)

As for any notes/examples:
There is a description on the project page: http://cultrarius.github.io/QuestWeaver/

Basically you have to create a custom `WorldModel` (see `SpaceWorldModel` for an example) that "knows" your game world and provides entities for the quest system. But the quest system will also want to create new entities, so your world model really is both ways and also affects the game.

For the templates, you need 3 things: a factory that creates teamplate objects (see `SpaceQuestTemplateFactory.cpp` for an example), the template objects (e.g. `ExploreRegionTemplate.cpp`) that know which elements to pick from your world model to create a particular quest and lastly the template file itself (e.g. `ExploreRegionTemplate.qt`) which defines variants for the quest description and title, says how rare it is, etc.

The most interesting thing however is the story generator! :)
Similar to the quests, you have a factory (see `CommonSpaceStoryFactory.cpp`) and a template class (`PlanetIntroStoryTemplate.cpp`) and two story files: the story "nuggets", which are the juicy parts of the story (`Resources/Space/Nuggets.st`) and a file which says how the nuggets are combined for different stories (`CommonSpaceStories.st`).

Another good starting point are the unit tests, you can for example have a look at the `TemplateTest.cpp` or the `StoryWriterTest.cpp`.

I can also create a small example project to get you started if you tell me a little more about what you want to do.
